### ISSUE TITLE
学长太强了！！那个引诱别人下禁手的部分是咋写的啊，而且为啥你的C语言是大一学的？

### ISSUE THREAD

**Issue by daidailindaiyu** [yfchen7/Five-to-five-Renju#1]

**Comment by yfchen7** [comment]
大群qq找我私聊，信息自寻。

**Comment by daidailindaiyu** [comment]
抱歉学长，我放弃找到你了，骚扰了大群里一个19的同学结果发现不是。
你的有效信息太少了吧，只有一个id和一个缩写，但是缩写那三个字母应该也不是你名字吧，要不就是没在大群里实名，能不能再给点线索。我现在甚至都还没搞明白你是哪一级的，虽然按照修改时间来看大三的可能性比较大

**Comment by yfchen7** [comment]
https://github.com/UCAS-schoolwork/UCAS-CS-experience/tree/master/%E4%B8%93%E4%B8%9A%E5%BF%85%E4%BF%AE%E8%AF%BE/C%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E8%AF%AD%E8%A8%80/ylx%E7%8F%AD
我的程序只实现了简单剪枝+棋步排序+简单算杀。下一个提升比较大的方法可能是哈希。
算的层数多了，自然就能看到怎么走能让对手走到禁手了。
